### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by luojing1030** [mahmoodlab/HIPT#11]
Thank you for the great work and for sharing the code.

I have noticed that the datasets used in this article (NSCLSC and RCC) have been used in other articles of the author. Here I have a question to ask whether there is any overlap between the pretraining data and the datasets. Of course, if possible, can the author provide the manifest files of the respective TCGA datasets（I say this because I download TCGA datasets through the manifest file, so I record the ID of each WSI slide,and I want to use these two data sets as a task, so I want to match the data you use）？ If possible, I can email you, and then you can tell me by email. Please forgive me for my poor language ability.

**Comment by Richarizardd** [comment]
Hi @luojing1030 - thank you for commenting. I can provide the manifest for NSCLC and RCC. What is your email?

**Comment by luojing1030** [comment]
Thank you for your reply. I'm the user of luojing1030. My email ***@***.***


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mahmoodlab/HIPT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月25日(星期一) 凌晨2:14
***@***.***&gt;;
抄送:&nbsp;"@***@***.******@***.***&gt;;
主题:&nbsp;Re: [mahmoodlab/HIPT] Datasets (Issue #11)





 
Hi @luojing1030 - thank you for commenting. I can provide the manifest for NSCLC and RCC. What is your email?

**Comment by Richarizardd** [comment]
@luojing1030 - it may be better to just email me directly (see README).

**Comment by Richarizardd** [comment]
For posterity - here are the GDC manifests for downloading the slides in the subtypting tasks.
- [gdc_manifest_brca.txt](https://github.com/mahmoodlab/HIPT/files/9177519/gdc_manifest_brca.txt)
- [gdc_manifest_lung.txt](https://github.com/mahmoodlab/HIPT/files/9177517/gdc_manifest_lung.txt)
- [gdc_manifest_kidney.txt](https://github.com/mahmoodlab/HIPT/files/9177518/gdc_manifest_kidney.txt)
