### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.gpu_utils'

### ISSUE THREAD

**Issue by mastermert** [mahmoodlab/HIPT#18]
Hello; I am trying to reproduce results in 'Weakly-Supervised Training + Evaluation' section however when I run code, I am facing with this error. There is no file named `gpu_utils` under `HIPT/ 2-Weakly-Supervised-Subtyping/ utils`. I also checked CLAM and MCAT GitHub repos but could not find the file under utils files.

**Comment by Richarizardd** [comment]
HI @mastermert - Sorry for the confusion. The ```gpu_utils``` file was extraneous code that was missing, and I have simply commented it out now. In addition, for reproducibility issues, see #25 for any concerns.
