### ISSUE TITLE
Which mean "n" and "h" ?

### ISSUE THREAD

**Issue by AndrewTal** [mahmoodlab/HIPT#22]
ViT4096-256(n = 4, h = 3, d = 192)
ViTWSI-4096(n = 2, h = 3, d = 192) 

Hi, which mean "n" and "h" ?

**Comment by AndrewTal** [comment]
'h' is attention heads. what is 'n'?

**Comment by Richarizardd** [comment]
Hi @AndrewTal - n == # of layers.
