### ISSUE TITLE
Inquiry about Dataset

### ISSUE THREAD

**Issue by bryanwong17** [mahmoodlab/HIPT#26]
Hi Richard,

Could you please let me know how to download the same datasets as yours? Additionally, I tried git cloning your repository, but I couldn't unzip all zip folders in _HIPT/2-Weakly-Supervised-Subtyping/dataset_csv_. What is the procedure for unzipping it? Thank you

**Comment by Richarizardd** [comment]
Hi @bryanwong17 - I perhaps saved the CSV files in an unconventional way (saved previously for storing the count matrices / RNA-seq abundances for all 20K-ish genes). You can open the dataset CSV files via `pandas`.

**Comment by bryanwong17** [comment]
Hi @Richarizardd,

Thanks for your fast reply. I was able to open the dataset CSV files and see all slide_ids. Should I manually download them one by one in order to download all of them? Is there a better way?

**Comment by Richarizardd** [comment]
I think the best way to download is via [https://portal.gdc.cancer.gov](https://portal.gdc.cancer.gov). I would query by the cancer type, get a "manifest" of all diagnostic WSIs for that cancer type, and then download slides from the manifest. Then, afterwards, one can align the downloaded WSIs with the `slide_id` column.

**Comment by bryanwong17** [comment]
Is there a need to log in before downloading slides from the manifest? Can the public download the files from the website?

**Comment by syy-create** [comment]
> I think the best way to download is via https://portal.gdc.cancer.gov. I would query by the cancer type, get a "manifest" of all diagnostic WSIs for that cancer type, and then download slides from the manifest. Then, afterwards, one can align the downloaded WSIs with the `slide_id` column.

Hello, after downloading the BRCA dataset from gdc, what should I do to obtain the mapping between IDC and ILC, if it is not applicable to the CSV table you provided,hanks.
