### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by bryanwong17** [mahmoodlab/HIPT#27]
Hi @Richarizardd,

I would be glad if you can answer some of my questions below:

1. Before running main_dino4k.py, I notice you saved all [256-Length x 384-Dim] Tensors for the input which correspond to extracted ViT-16 features for 4K x 4K patch. May I know in which part of the code you did that? Do I need to extract patches of 4k x 4k in jpg or png format to get the input tensors?

2. Should I change the equation below if batch size=64 couldn't be used? How about the learning rate?

args.lr * (args.batch_size_per_gpu * utils.get_world_size()) / 256.

3. Is **HIPT_LGP_FC** your main model?

Thanks for your time and kindness!

**Comment by Richarizardd** [comment]
1. 4K feature extraction can be performed via modifying CLAM to do 4K patching (instead of 256 patching - simply pass in the patch_size = 4096), followed by using the ```HIPT_4K``` API as the feature extractor.
2. I think you can keep the equation as-is.
3. ```HIPT_LGP_FC``` is the main model.

**Comment by bryanwong17** [comment]
Hi @Richarizardd , thanks for your answers. Would you mind pointing out which one is HIPT_4K API? According to HIPT_4k class, the input dimension is torch.Size([1, 3, 4096, 4096]), and the output dimension is torch.Size([1, 192]), which is the output of VIT 4k-256. Nonetheless, I need the output from VIT 256-16, which has the dimension torch.Size([256, 384]) which will be used as the input of main_dino4k.py .Should I uncomment some code in HIPT_4K? Please let me know if there is something wrong with my explanation. Thank you.
