### ISSUE TITLE
Getting raw patches after CLAM preprocessing

### ISSUE THREAD

**Issue by bryanwong17** [mahmoodlab/HIPT#28]
Hi @Richarizardd,

May I know how to get raw [256 × 256] patches (as *.png format) after CLAM processing?

**Comment by bryanwong17** [comment]
Hi @Richarizardd, I tried using this command:

python create_patches.py --source  DATA_DIRECTORY --save_dir RESULTS_DIRECTORY  --patch_size 256 --seg --patch --stitch

However, I still couldn't get raw [256 x 256 patches] (as *.png format). Is there something wrong?

**Comment by clemsgrs** [comment]
hi @bryanwong17, my understanding is that `create_patches.py` will store image patches as numpy arrays under the `imgs` dataset in the `h5py` file saved to disk. 
You can either:
- write a small script that opens each `h5py` file & save corresponding numpy arrays to disk as png images

- add the following lines [here](https://github.com/mahmoodlab/CLAM/blob/6fbcaa38d79e69f83dd463527093848fa4aa5091/wsi_core/wsi_utils.py#L38) and re-run `create_patches.py` (it'll save each patch based on its `x` and `y` coordinates)
```
pil_patch = Image.fromarray(img_patch)
patch_save_path = os.path.join(save_path, name, f'{x}_{y}.png')
if not os.path.isdir(os.path.join(save_path, name)):
      os.mkdir(os.path.join(save_path, name))
pil_patch.save(patch_save_path)
```

hope it was helpful

**Comment by bryanwong17** [comment]
Hi @clemsgrs, Thank you for helping. I really appreciate it. I tried re-running create_patches.py with additional code from you. However, I received the following error message:

AttributeError: 'WholeSlideImage' object has no attribute 'holes_tissue'

Do you have any idea why this happens? FYI, I'm using CAMELYON16

**Comment by bryanwong17** [comment]
@clemsgrs Do you have any ideas on how to fix this error? Thanks

Traceback (most recent call last):
  File "C:\CLAM\create_patches.py", line 286, in <module>
    seg_times, patch_times = seg_and_patch(**directories, **parameters,
  File "C:\CLAM\create_patches.py", line 178, in seg_and_patch
    file_path, patch_time_elapsed = patching(WSI_object = WSI_object, **current_patch_params)
  File "C:\CLAM\create_patches.py", line 41, in patching
    file_path = WSI_object.createPatches_bag_hdf5(**kwargs, save_coord=True)
  File "C:\CLAM\wsi_core\WholeSlideImage.py", line 263, in createPatches_bag_hdf5
    savePatchIter_bag_hdf5(patch)
  File "C:\CLAM\wsi_core\wsi_utils.py", line 41, in savePatchIter_bag_hdf5
    pil_patch = Image.fromarray(img_patch)
  File "C:\Users\user\anaconda3\envs\hipt\lib\site-packages\PIL\Image.py", line 2955, in fromarray
    raise TypeError("Cannot handle this data type: %s, %s" % typekey) from e
TypeError: Cannot handle this data type: (1, 1, 256, 3), |u1

**Comment by bryanwong17** [comment]
Hi @clemsgrs, I was able to extract patches in .png format. In this case, what do x and y represent? Are they representing the **actual** location in the slide? Does that mean we do not have to multiply again, let's say with 256?

![image](https://user-images.githubusercontent.com/67773304/208889129-80b07147-b505-4765-82e6-2aba0ade800a.png)

**Comment by clemsgrs** [comment]
hi, yes `x` and `y` coordinates should represent the true location in the slide **at the level at which patching was computed**.

**Comment by ShiCrazy** [comment]
> hi @bryanwong17, my understanding is that `create_patches.py` will store image patches as numpy arrays under the `imgs` dataset in the `h5py` file saved to disk. You can either:
> 
> * write a small script that opens each `h5py` file & save corresponding numpy arrays to disk as png images
> * add the following lines [here](https://github.com/mahmoodlab/CLAM/blob/6fbcaa38d79e69f83dd463527093848fa4aa5091/wsi_core/wsi_utils.py#L38) and re-run `create_patches.py` (it'll save each patch based on its `x` and `y` coordinates)
> 
> ```
> pil_patch = Image.fromarray(img_patch)
> patch_save_path = os.path.join(save_path, name, f'{x}_{y}.png')
> if not os.path.isdir(os.path.join(save_path, name)):
>       os.mkdir(os.path.join(save_path, name))
> pil_patch.save(patch_save_path)
> ```
> 
> hope it was helpful

Hello @clemsgrs , thank you for your supplementary codes firstly. I tried it but an error occurred, just like this
————————
Traceback (most recent call last):
  File "/data/home/OM/shigb/.local/lib/python3.8/site-packages/PIL/Image.py", line 3080, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 256, 3), '|u1')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "create_patches.py", line 281, in <module>
    seg_times, patch_times = seg_and_patch(**directories, **parameters,
  File "create_patches.py", line 173, in seg_and_patch
    file_path, patch_time_elapsed = patching(WSI_object = WSI_object, **current_patch_params)
  File "create_patches.py", line 36, in patching
    file_path = WSI_object.createPatches_bag_hdf5(**kwargs, save_coord=True)
  File "/wz-pstor02/Shigb_CLAM_FGFR/clam_ostu_fgfr_beta/wsi_core/WholeSlideImage.py", line 263, in createPatches_bag_hdf5
    savePatchIter_bag_hdf5(patch)
  File "/wz-pstor02/Shigb_CLAM_FGFR/clam_ostu_fgfr_beta/wsi_core/wsi_utils.py", line 38, in savePatchIter_bag_hdf5
    pil_patch = Image.fromarray(img_patch)
  File "/data/home/OM/shigb/.local/lib/python3.8/site-packages/PIL/Image.py", line 3083, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1, 256, 3), |u1
————————

I do not understand the meaning, maybe you have some advice?
