### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by jasonyin20** [mahmoodlab/HIPT#30]
thanks you for your open source but i  have some questions 
![image](https://user-images.githubusercontent.com/54090559/206062761-4114370a-3589-4dc6-aab4-d2073d507ce2.png)
where is the function of get_patch_attention_scores.I can't find that

**Comment by Arkkienkeli** [comment]
Hi @jasonyin20 , I am not a maintainer, but I also had some issues with the notebook (see #29). 
I have put together a PR https://github.com/mahmoodlab/HIPT/pull/31 - now the notebooks seems to work, but I did not test other parts of the code. With that I could run it. It uses CPU only.
