### ISSUE TITLE
Number of epochs required for finetuning

### ISSUE THREAD

**Issue by bryanwong17** [mahmoodlab/HIPT#33]
Hi, My goal is to fine-tune a DINO 1st stage model from a checkpoint folder (vit256_small_dino.pth) using the Camelyon16 dataset. For an optimal solution, how many epochs are needed?

**Comment by Richarizardd** [comment]
@bryanwong17 - from my experience working with DINO, 100 epochs would be the bare minimum that I would try and evaluate models on (assuming the # of images in your dataset is around ~1M). 300 epochs seems to be a good intermediate checkpoint, with other models trained for 800/1600 epochs (you can always train for longer).

While I did not initialize my ViT model with ImageNet weights, I imagine one can see faster convergence if your initial ViT model weights were already pretrained as well!
