### ISSUE TITLE
'Weakly-Supervised Training' task - Issue with fast_cluster_ids.pkl file

### ISSUE THREAD

**Issue by gaiacervi** [mahmoodlab/HIPT#34]
Hello, 
Thank you for the great work and the released code. I am trying to perform the training of the ViT-WSI to get a slide-level classification on a customized dataset. Even though I have structured the `TCGA_ROOT_DIR` folder as shown in the README and adapted the code in the main.py file to my use-case by adding the following lines
 

           
              elif args.task == 'tcga_h_subtype':
                          args.n_classes = 2

                           dataset = Generic_MIL_Dataset(csv_path = './dataset_csv/tcga_h_subset.csv',
                                                                              data_dir= os.path.join(args.data_root_dir, study_dir),
                                                                              mode=args.mode, 
                                                                              shuffle = False, 
                                                                              seed = args.seed, 
                                                                              print_info = True,
                                                                              label_col='oncotree_code',
                                                                              label_dict = {0:0, 1:1},
                                                                              patient_strat=False,
                                                                              prop=args.prop) ` 

when running the command 

 `CUDA_VISIBLE_DEVICES=$GPU python main.py --data_root_dir $DATAROOT --model_type hipt_lgp --task $TASK --prop 1.0 --pretrain_4k vit4k_xs_dino --freeze_4k`  

I get the following error ` File "HIPT/2-Weakly-Supervised-Subtyping/datasets/dataset_generic.py", line 411, in __init__
with open(os.path.join(cluster_dir, 'fast_cluster_ids.pkl'), 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: data_dir/extracted_mag20x_patch4096_fp/fast_cluster_ids.pkl'. ` ` `

Which script should I run to produce this file? What does it represent? I cannot find any indication in the README. 

Moreover, I noticed that in line 123 and 125 on main.py file, the `args.pretrain_WSI` argument is called but it is not specified in the arg.parser.

Thanks!!

**Comment by JuanDuranMcgill** [comment]
Hello, I am also trying to re-create the folder structure TCGA_ROOT_DIR but I am having a hard time at the moment. Do you mind sharing with me how you did it? It would mean the world to me. Please feel free to message me at juan.duran@mail.mcgill.ca, Thank you!

**Comment by Richarizardd** [comment]
Hi @gaiacervi - apologies. I updated the repository to remove the` fast_cluster_ids.pkl` requirement (needed for running one of the baselines).

Regarding `args.pretrain_WSI`, that argument is for eventual slide-level pretraining with HIPT.
