### ISSUE TITLE
Process of training subtyping task on custom WSIs dataset using provided pretrained model

### ISSUE THREAD

**Issue by SongDoHou** [mahmoodlab/HIPT#35]
Hi, thank you for your wonderful work and sharing the codes.

We hope to use provided feature extractor on our own dataset. (_i.e._, Skip the self-supervised learning process.)

However, we are not clear about how to organize the folders for weakly-supervised training on our own dataset.

We'd like to ask you how to construct folder like this, by modifying CLAM's ```create_patches_fp.py``` and ```extract_features_fp.py```.
```bash
Custom_Dataset_Features_Folder/
    ├── h5_files
            ├── slide_1.h5
            ├── slide_2.h5
            └── ...
    └── pt_files
            ├── slide_1.pt
            ├── slide_2.pt
            └── ...
 ```

or if we are not correct, can you provide the codes or details for weakly-supervised training setup?

Thank you!

**Comment by JuanDuranMcgill** [comment]
Hello, I am currently trying to re-create the code for weakly supervised training for subtyping. Have you managed to set up everything for the structure in TCGA_ROOT_DIR? I am having trouble and if you could share with me how you did it, it would mean a lot. feel free to message me at juan.duran@mail.mcgill.ca, Thank you!

**Comment by Richarizardd** [comment]
Hi @SongDoHou @JuanDuranMcgill. In` extract_features_fp.py`, you can modify the code so that instead of patching at [256 x 256], you can patch at [4096 x 4096]. After you have coords for [4096 x 4096] patches, you can use the `HIPT_4K` API to replace the `resnet50_trunc` encoder for feature extraction.
