### ISSUE TITLE
How can I get ’vits_tcga_pancancer_dino_pt_patch_features‘?

### ISSUE THREAD

**Issue by qidog** [mahmoodlab/HIPT#42]
How can I make the size of .pt is M*256*384, not M*192. Can u open your change on CLAM or show me some help about how to create the dataset?

**Comment by Richarizardd** [comment]
HI @qidog - would you be able to re-explain your question? In case it would help, here is a [directory of all 192-dim feature embeddings for 4K x 4K regions](https://github.com/mahmoodlab/HIPT/tree/master/3-Self-Supervised-Eval/embeddings_slide_lib/embeddings_slide_lib/vit256mean_tcga_slide_embeddings) for TCGA.

**Comment by ekansh09** [comment]
Hello @Richarizardd,

Could you please guide me on how to extract vits_tcga_pancancer_dino_pt_patch_features for every 4096 x 4096 patches and save them in the extracted_mag20x_patch4096_fp folder?

Also, I was wondering if there is a feature extraction pipeline available for this task, or do we need to extract features for each 4096 x 4096 patch using HIPT_4k api and then vstack all of them? If you have a code for this, it would be great if you could share it.

Thank you!
