### ISSUE TITLE
Batch-wise extract features

### ISSUE THREAD

**Issue by SongDoHou** [mahmoodlab/HIPT#44]
Hello,

I'm trying to extract and save features using HIPT/hipt_4k.py codes. However, It seems to works for only a 1-batch size. 
Do you have any suggestions or tips for modifying the code to allow for batch-wise processing?

Thank you!

**Comment by bguetarni** [comment]
I've also encountered the same problem. It only requires a few changes to the `forward` function of the HIPT_4K class.

I just changed this line to account for batch:
https://github.com/mahmoodlab/HIPT/blob/b5f4844f2d8b013d06807375166817eeb939a5aa/HIPT_4K/hipt_4k.py#L73
into this :
`features_cls256 = rearrange(features_cls256, '(b p1 p2) c -> b c p1 p2', b=bsize, p1=w_256, p2=h_256)`

Make sure to get the batch size of the input beforehand.

You alos have to adapt the `prepare_img_tensor` function to transform all the images in the batch from
https://github.com/mahmoodlab/HIPT/blob/b5f4844f2d8b013d06807375166817eeb939a5aa/HIPT_4K/hipt_4k.py#L329
into
`img_new = torch.stack(list(map(transforms.CenterCrop(load_size), img)))`

Hope it helps.

**Comment by Rainydu184** [comment]
@bguetarni  Great job! It is indeed useful when the length of a batch is a multiple of the batch size.

**Comment by Rainydu184** [comment]
@bguetarni I have check the results, they are different from the original.

**Comment by Rainydu184** [comment]
@bguetarni  It is indeed useful when the length of a bag is a multiple of the batch size.  However, when the bag length is not a multiple of the batch size, will get error in the last epoch.

**Comment by XinyangHan** [comment]
@Rainydu184 Yeah! If the bag length is not a multiple of the batch size, there would be an error. But only using batchsize as one would be tooooo slow. May I ask how should we handle that?
