### ISSUE TITLE
Using the Features in CLAM

### ISSUE THREAD

**Issue by shubhaminnani** [mahmoodlab/HIPT#46]
Hi @Richarizardd ,
Thanks for the great work. 
I am trying the subtyping part from the repository. I want to ask you if the features for slide having dimension NX192, where N is number of patches provided here https://github.com/mahmoodlab/HIPT/tree/master/3-Self-Supervised-Eval/embeddings_slide_lib/embeddings_slide_lib/vit256mean_tcga_slide_embeddings 

Q1 : can be used directly in the CLAM training pipeline provided in the subtyping part?

Q2 : if we want touse the hipt_lgp or hipt_n models from the repo, we would need to feed them with NX384 features also? I am assuming this are not provided in the repository ?

Q3 : When we extract patches with 4096 will give us features 192, and when we extract patches at 256 it will give us features at 384?
When we extract features from 4096 from VIT4K, and for 256 size patches from VIT256, when I tried to extract features from VIT256, features size still was still as N X 192. Is there anything need to be changed while extracting VIT 256 features?
 
Thanks!

**Comment by Arkkienkeli** [comment]
Q3: Feature-vector size related to the size of ViT: S (small) - feature size 192 and B (base) with feature size 384. Look at the checkpoint names. Feature size does not depend on input size.

**Comment by Richarizardd** [comment]
Hi @shubhaminnani - yes, these features can directly be plug-and-played in CLAM. See a similar thread here. https://github.com/mahmoodlab/HIPT/issues/25. If you want to use other features into HIPT_LGP, you would need to adjust the token dimension accordingly, however, the ViT-S/B/L/H/G architectures have fixed token dimensions (that you could modify yourself), but may be inflexible for pretraining.
