### ISSUE TITLE
VIT-4096-WSI

### ISSUE THREAD

**Issue by arjun11verma** [mahmoodlab/HIPT#50]
What would y'all recommend to use for VIT4096-WSI? I ended up just using an adjusted wrapper of the VisionTransformer4K class, but I feel as if this isn't the best solution.

**Comment by Richarizardd** [comment]
For the "global aggregator" of the 4K features, you could stack another ViT, but one can also stack much simpler feature aggregators such as ABMIL and other permutation-invariant pooling architectures.
