### ISSUE TITLE
dino4k pretraining

### ISSUE THREAD

**Issue by Akihiko0123** [mahmoodlab/HIPT#60]
Thank you very much for sharing this excellent study.
We are interested in training this model by using our pathological images.

I trained main_dino.py model by inputting 256x256 patches as step 1.
Then we are considering to train main_dino4k.py model by inputting feature (tensor) from 4096x4096 patches as step 2.

To do this, I consider we need to use create_patches_fp.py and extract_features_fp.py to extract features from WSIs as input of main_dino4K.py.
Also, my understanding is that we need to use VisionTransformer4K class in extract_features_fp.py.

However, when I tried to extract features by using Visiontransformer4K after making 4096x4096 patches from create_patches_fp.py, I got the following out of memory error. (We use single A100 GPU. )

```
RuntimeError: CUDA out of memory. Tried to allocate 384.01 GiB (GPU 0; 39.59 GiB total capacity; 884.80 MiB already allocated; 34.87 GiB free; 990.00 MiB reserved in total by PyTorch)
```

I believe this happened due to processing big size patches(4096x4096).

Would you mind letting me know if my above process is right to train dino_4k.py?
I would appreciate it if you could let me know the right process to train HIPT models. 
Thank you.

**Comment by ShiCrazy** [comment]
Arrange batch_size to a smaller number, like 1?

**Comment by Akihiko0123** [comment]
@ShiCrazy 
Thank you so much for your advice. I apologize for the lack of information. 
The above result I posted is the result of  running the program with batch size 1.

**Comment by ShiCrazy** [comment]
I did not try using VisionTransformer4k class to extract features, maybe you can try HIPT_4K class？I am not clear about the difference between two classes, but HIPT_4K class really works when used to extracted features. 

# 51 You can see the issue. I have extracted features by following the instructions step by step successfully

**Comment by Akihiko0123** [comment]
@ShiCrazy 
I appreciate for your nice advice.
It seems that the program started working by using HIPT_4K class instead of VisionTransformer4k class. I will try to follow #51.
Thank you again.
