### ISSUE TITLE
Pretrained-WSI

### ISSUE THREAD

**Issue by lvyiwei1** [mahmoodlab/HIPT#7]
Thank you for your great work on the HIPT model!

In HIPT_LGP_FC, it seems that the code for loading pretrained-WSI is just "pass". Is there a way to load pretrained-WSI? Also, is the pretrained model for this part included in the repository?

**Comment by Richarizardd** [comment]
Hi @lvyiwei1 

At the moment - pretraining the slide-level ViT is not possible (not enough data points). I coded this functionality as it may be something that would be supported in the near future (having not just pretrained ViT_256-16 and ViT_4K-256 weights, but also ViT_WSI-4K weights!).

**Comment by lvyiwei1** [comment]
Thank you so much for your quick reply! Would it be possible to share a trained slide-level ViT on the subtyping task?
