### ISSUE TITLE
what is the mean and std when using the pretrined dino vit-s to extract patch feature?

### ISSUE THREAD

**Issue by weiaicunzai** [mahmoodlab/HIPT#70]
HI, thanks for your great work. I'm currently using your pretrained dino network backbone (ViT-S/16) to extract patch (256x256) features. 
What mean and std should I use?
ImageNet mean and std `mean = (0.485, 0.456, 0.406) & std = (0.229, 0.224, 0.225)` ?
Or
`mean = (0.5,0.5,0.5) & std = (0.5,0.5,0.5)`?

Thanks

![image](https://github.com/mahmoodlab/HIPT/assets/1770114/2f98b26d-0675-465c-98c2-3b4bdbcc51c0)

**Comment by Richarizardd** [comment]
Hi @weiaicunzai  - you should use mean = (0.5,0.5,0.5) & std = (0.5,0.5,0.5) as defined in loading the model weights for HIPT.
