### ISSUE TITLE
Survival Code

### ISSUE THREAD

**Issue by pazadimo** [mahmoodlab/HIPT#9]
Hi,
Thanks for sharing the code.
It seems that hipt_lgp is implemented in the MCAT repo yet, but it says in this repo that we should use the below command which I assume is related to MCAT repo(Please correct me if I'm wrong):

`python main.py --data_root_dir $DATAROOT --which_splits 5foldcv --split_dir tcga_brca --mode pyramid --model_type hipt_lgp --pretrain_4k vit4k_xs_dino --freeze_4k`

 I wonder if you can provide more info on how to use MCAT code with hipt_lgp backbone for survival prediction especially when there is no omics data available in the dataset? or the main file with other required files for this task.

Thanks.

**Comment by Richarizardd** [comment]
Hi @pazadimo - will send an update soon. I am still thinking whether it would be better to re-hash the MCAT survival code in this repository, or update MCAT with the hipt_lgp method (leaning towards the former than the latter).

**Comment by zzbuzzard** [comment]
Hi @Richarizardd been a while but would appreciate an update here; it's really unclear how to actually run HIPT for survival prediction as things are at the moment.

**Comment by rashindrie** [comment]
Hi, 

@Richarizardd Just wondering if you could share the modified MCAT code for survival prediction. Would be great to have it. 

TIA
